# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPods
  
  pod 'CombineX/CXFoundation', :path => '../../../'

end
