#!/bin/bash

echo "copy..."

cp ci/Package.swift Package.swift

echo "generate xcodeproj..."

swift package generate-xcodeproj

echo "test..."

xcode_project="CombineX.xcodeproj"
xcode_scheme="CombineX-Package"
xcode_destination="platform=iOS Simulator,OS=13.1,name=iPhone 8"

xcodebuild test -project "$xcode_project" -scheme "$xcode_scheme" -destination "$xcode_destination"
