install! 'cocoapods', :generate_multiple_pod_projects => true

source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

def pod_quick
  pod 'Quick'
  pod 'Nimble'
end

target 'Specs' do
  
  use_frameworks!

  target 'SpecsTests' do
    inherit! :search_paths
    
    pod_quick
  end

end

target 'CombineX' do
  
  use_frameworks!
  
  target 'CombineXTests' do
    inherit! :search_paths
    
    pod_quick
  end

end
